from __future__ import annotations

import os
from pathlib import Path

from sqlalchemy import create_engine, text

from config import DATABASE_URL, DB_PATH, ensure_data_dir, is_postgres

_ENGINE = None


def url(db_path: str | Path | None = None) -> str:
    if is_postgres():
        return str(DATABASE_URL)
    ensure_data_dir()
    path = Path(db_path or DB_PATH).expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    return f"sqlite:///{path}"


def engine(db_path: str | Path | None = None):
    global _ENGINE
    if db_path is not None:
        return create_engine(url(db_path), future=True)
    if _ENGINE is None:
        kwargs = {"pool_pre_ping": True, "future": True}
        if is_postgres():
            kwargs["connect_args"] = {"sslmode": "require"}
        _ENGINE = create_engine(url(), **kwargs)
    return _ENGINE


def pk() -> str:
    return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if is_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"


def rows(items):
    return [dict(item._mapping) for item in items]
