from __future__ import annotations

from sqlalchemy import text

from config import is_postgres
from db_constants import DEFAULT_CATEGORIES
from db_state import engine


def _pk() -> str:
    if is_postgres():
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def init_tables(db_path=None) -> None:
    pk = _pk()
    with engine(db_path).begin() as conn:
        conn.execute(text(f"CREATE TABLE IF NOT EXISTS users_app (id {pk}, username TEXT UNIQUE NOT NULL, access_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin','coach')), created_at TEXT DEFAULT CURRENT_TIMESTAMP)"))
        conn.execute(text(f"CREATE TABLE IF NOT EXISTS budget_categories (id {pk}, name TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('income','expense')), allocated FLOAT NOT NULL DEFAULT 0, month TEXT NOT NULL, UNIQUE(name, month))"))
        conn.execute(text(f"CREATE TABLE IF NOT EXISTS transactions_app (id {pk}, date TEXT NOT NULL, description TEXT NOT NULL, amount FLOAT NOT NULL, category_id INTEGER, account_number TEXT, raw_data TEXT, source TEXT DEFAULT 'manual', month TEXT NOT NULL)"))
        conn.execute(text(f"CREATE TABLE IF NOT EXISTS business_ledger (id {pk}, date TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('revenue','expense')), amount FLOAT NOT NULL, month TEXT NOT NULL)"))


def seed_categories(month: str) -> None:
    with engine().begin() as conn:
        for name, kind, amount in DEFAULT_CATEGORIES:
            exists = conn.execute(text("SELECT id FROM budget_categories WHERE name = :name AND month = :month"), {"name": name, "month": month}).fetchone()
            if exists is None:
                conn.execute(text("INSERT INTO budget_categories(name, type, allocated, month) VALUES (:name, :kind, :amount, :month)"), {"name": name, "kind": kind, "amount": amount, "month": month})
